services:
  db:
    image: mysql:latest
    volumes:
            - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3906:3306"
    expose:
      - "3906"
    environment:
     - "MYSQL_ROOT_PASSWORD=${DB_PASS}"
    networks:
      - libmansys
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 3
      interval: 5s
      timeout: 15s
    restart: always

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./database/migration:/migration
    networks:
      - libmansys
    command:
      [
        "-path",
        "/migration",
        "-database",
        "mysql://root:${DB_PASS}@tcp(db:3306)/lib_db",
        "up"
      ]

  libmansys:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - libmansys
volumes:
  db:
  migrate:
networks:
  libmansys:
    driver: bridge
