.DEFAULT_GOAL:= help

help:
	@echo "build -builds the project"
	@echo "run -runs the project withou building it"
	@echo "clean -removes the binary file"
	@echo "help - displays this help message"
	@echo "migrate_create -creates a new migration"
	@echo "migrate_up -runs the migration up"
	@echo "migrate_down -runs the migration down"

build:
	@echo "Building the project"
	go build -o ./mvc cmd/main.go
	@echo "Build complete"

run:
	@echo "Running the project"
	go run cmd/main.go

clean:
	@echo "Removing the binary file"
	rm -f ./mvc

migrate_create:
	@echo "Creating a new migration"
	migrate create -ext sql -dir database/migration -seq init
# The migration_up and migration_down will appear here after running startup.sh
